### ISSUE TITLE
Dataset Private

### ISSUE THREAD

**Issue by devinjnugraha** [TheBeastCoding/standardized-multichannel-dataset-glaucoma#10]
Hi, I'm doing an academic research with this dataset to investigate the usage of weighted loss on imbalance dataset. Lately, I found out that this dataset is private in Kaggle. Would you mind to make this dataset public? It really matters to me, thank you for your kind attention.

**Comment by TheBeastCoding** [comment]
Hey there! Thank you for your comment. Unfortunately the Kaggle team had flagged the dataset for competition rule violation (they cited a diabetic retinopathy competition of all things lol). Please be patient while I attempt to resolve this claim so that the dataset can be public again!

**Comment by devinjnugraha** [comment]
Thank you so much for your response and for working to resolve this issue. I really appreciate your efforts in making the dataset public again.
